site_name: torch_jax_interop Documentation
site_url: https://lebrice.github.io/torch_jax_interop
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.pytest.org/en/stable/objects.inv
            - https://flax.readthedocs.io/en/latest/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
            - https://jax.readthedocs.io/en/latest/objects.inv
          options:
            docstring_style: numpy
            members_order: source
            annotations_path: brief
            show_docstring_attributes: true
            modernize_annotations: true
            show_source: false
            show_submodules: false
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
            allow_inspection: true
